version: "3.9"

services:
  api:
    build: ./backend
    container_name: mm_api
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - influx
    volumes:
      - ./backend:/app
    networks:
      - mm_net

  worker:
    build: ./backend
    container_name: mm_worker
    restart: unless-stopped
    command: celery -A app.tasks.celery_app worker --loglevel=info --concurrency=8
    env_file: .env
    depends_on:
      - db
      - redis
      - influx
    volumes:
      - ./backend:/app
    networks:
      - mm_net

  scheduler:
    build: ./backend
    container_name: mm_scheduler
    restart: unless-stopped
    command: celery -A app.tasks.celery_app beat --loglevel=info --scheduler redbeat.RedBeatScheduler
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./backend:/app
    networks:
      - mm_net

  frontend:
    build: ./frontend
    container_name: mm_frontend
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - mm_net

  db:
    image: postgres:16-alpine
    container_name: mm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mm_net

  influx:
    image: influxdb:2.7-alpine
    container_name: mm_influx
    restart: unless-stopped
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUX_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN}
    volumes:
      - influx_data:/var/lib/influxdb2
    networks:
      - mm_net

  redis:
    image: redis:7-alpine
    container_name: mm_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - mm_net

  nginx:
    image: nginx:alpine
    container_name: mm_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - frontend
    networks:
      - mm_net

volumes:
  pg_data:
  influx_data:
  redis_data:

networks:
  mm_net:
    driver: bridge
